/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedLavajatoRouteImport } from './routes/_authenticated/lavajato'
import { Route as AuthenticatedPatioRouteImport } from './routes/_authenticated/patio'
import { Route as AuthenticatedVagasRouteImport } from './routes/_authenticated/vagas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLavajatoRoute = AuthenticatedLavajatoRouteImport.update({
  id: '/lavajato',
  path: '/lavajato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatioRoute = AuthenticatedPatioRouteImport.update({
  id: '/patio',
  path: '/patio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVagasRoute = AuthenticatedVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/lavajato': typeof AuthenticatedLavajatoRoute
  '/patio': typeof AuthenticatedPatioRoute
  '/vagas': typeof AuthenticatedVagasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/lavajato': typeof AuthenticatedLavajatoRoute
  '/patio': typeof AuthenticatedPatioRoute
  '/vagas': typeof AuthenticatedVagasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/lavajato': typeof AuthenticatedLavajatoRoute
  '/_authenticated/patio': typeof AuthenticatedPatioRoute
  '/_authenticated/vagas': typeof AuthenticatedVagasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/despesas'
    | '/faturamento'
    | '/lavajato'
    | '/patio'
    | '/vagas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/despesas'
    | '/faturamento'
    | '/lavajato'
    | '/patio'
    | '/vagas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/despesas'
    | '/_authenticated/faturamento'
    | '/_authenticated/lavajato'
    | '/_authenticated/patio'
    | '/_authenticated/vagas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lavajato': {
      id: '/_authenticated/lavajato'
      path: '/lavajato'
      fullPath: '/lavajato'
      preLoaderRoute: typeof AuthenticatedLavajatoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patio': {
      id: '/_authenticated/patio'
      path: '/patio'
      fullPath: '/patio'
      preLoaderRoute: typeof AuthenticatedPatioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vagas': {
      id: '/_authenticated/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof AuthenticatedVagasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedLavajatoRoute: typeof AuthenticatedLavajatoRoute
  AuthenticatedPatioRoute: typeof AuthenticatedPatioRoute
  AuthenticatedVagasRoute: typeof AuthenticatedVagasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedLavajatoRoute: AuthenticatedLavajatoRoute,
  AuthenticatedPatioRoute: AuthenticatedPatioRoute,
  AuthenticatedVagasRoute: AuthenticatedVagasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
